### PR TITLE
Allow symfony-7 in composer.json

### PR DESCRIPTION
**Pull request by mkilmanas**
### Changes

This is simply allowing Symfony 7 in composer.json - could not find any problems or incompatibilities at this point.

- composer.json updated
- all tests (`composer test`) are passing
- tried it out on a minimal Symfony 7 project - no problems found
    - though I have only verified the JWT authentication use-case

### References

#182 

### Testing

Attempted to install this bundle on a small Symfony project and perform JWT authentication. Other use-cases should be verified.

Maybe instead of merging to `main` branch, this should be "quarantined" in a dedicated branch (e.g. `symfony7`) of this main repository - that way other people would be able to install this version via composer by requiring `auth0/symfony: dev-symfony7` and then test on their applications and their use-cases?

[ ] This change adds test coverage

[x] This change has been tested on the latest version of Symfony

### Checklist

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

[x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by evansims** [comment]
Hey @mkilmanas thanks a lot for contributing this; our team is at an offsite this week so my bandwidth is a little limited, but I'll take a look at this as soon as I'm back at my desk next week. Appreciate it!

**Comment by mkilmanas** [comment]
@evansims any chance to review this anytime soon? `auth0/symfony` is now the only remaining dependency blocking us from migrating to Symfony 7 on our projects

**Comment by mkilmanas** [comment]
Hey @evansims , is there anything happening at all? It's been over a month and no update.
Do we need to start considering a fork of this repo to have things moving? Or how else can we get support for up-to-date versions of Symfony?

**Comment by ip512** [comment]
@evansims do you think this PR could be merged shortly ? This could be a showstopper in the adaption of auth0 for some projects if this SDK is not compatible with sf7

**Comment by mkilmanas** [comment]
We have run out of patience and made a fork of this bundle -> https://packagist.org/packages/elvi/auth0-symfony

We will aim to maintain compatibility/updates as soon as they come to this official bundle, but also we will try to merge fixes/updates more proactively. No promises/guarantees though - still it's an open-source thing.

@gusdeboer @ip512 - feel free to give it a try (and any feedback welcome)

**Review by abunch — APPROVED** [review]

**Review by evansims — APPROVED** [review]

**Pull request merged**
